# Generated by Django 4.2.2 on 2023-06-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traits', '0001_initial'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='traits',
            field=models.ManyToManyField(to='traits.trait'),
        ),
    ]
